server:
  port: 9296

spring:
  application:
    name: RMS-CONFIG-SERVER
  cloud:
    config:
      server:
        #bootstrap: true
        git:
          uri: https://github.com/IKCONDev/rms-config-server
          clone-on-start: true
